---
- hosts: all
  become: yes
# This task is to create a new user and password 
  tasks:
    - name: Create a new user and set password
      user:
        name: "{{ uname }}"
        password: "{{ uname | password_hash('sha512') }}"
        groups: sudo
        append: yes
        shell: /bin/bash
        update_password: on_create
